# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decanter < Formula
  desc "Autolab from the CLI; Decan't you see why that's awesome?"
  homepage "https://github.com/p5quared/decanter"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/p5quared/decanter/releases/download/v0.2.7/decanter_Darwin_arm64.tar.gz"
      sha256 "644d8263a452b6550e749efb10409cf19fb8e40c0f9442b525d82233d93c466a"

      def install
        bin.install "decanter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/p5quared/decanter/releases/download/v0.2.7/decanter_Darwin_x86_64.tar.gz"
      sha256 "125e45a43d0becbe2025483d852082d56c250b4f17449545c258f64f1351dc9b"

      def install
        bin.install "decanter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/p5quared/decanter/releases/download/v0.2.7/decanter_Linux_arm64.tar.gz"
      sha256 "e5f04f0fc6a323e42b77dd972836982f3f2538135162bbd75d2b1dbe39a2b174"

      def install
        bin.install "decanter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/p5quared/decanter/releases/download/v0.2.7/decanter_Linux_x86_64.tar.gz"
      sha256 "96fa53b26cd12cbc063e067b74e8b506427da204a371b2bbc83c9c281ad5e7bb"

      def install
        bin.install "decanter"
      end
    end
  end
end
