# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decanter < Formula
  desc "Autolab from the CLI; Decan't you see why that's awesome?"
  homepage "https://github.com/p5quared/decanter"
  version "0.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/p5quared/decanter/releases/download/v0.2.10/decanter_Darwin_arm64.tar.gz"
      sha256 "6d9c5379b0ce3d2f2ed824dcd9713abdb014857729ef1b1366d55a0e1637113e"

      def install
        bin.install "decanter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/p5quared/decanter/releases/download/v0.2.10/decanter_Darwin_x86_64.tar.gz"
      sha256 "b66c203fbd57450d55d68c3f498bb5f96164e87afd621ad3d1974629c2b8eb10"

      def install
        bin.install "decanter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/p5quared/decanter/releases/download/v0.2.10/decanter_Linux_arm64.tar.gz"
      sha256 "7486d25befa50a7dfbe27970dcc59d4739efbb15b99da251e5ff46275c0b74bb"

      def install
        bin.install "decanter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/p5quared/decanter/releases/download/v0.2.10/decanter_Linux_x86_64.tar.gz"
      sha256 "bb1fdeaacc5b8fb62ea69ac9db6781da099a40e2d499f6f76eeb971b0a84df50"

      def install
        bin.install "decanter"
      end
    end
  end
end
